### ISSUE TITLE
Merge Commands

### ISSUE THREAD

**Issue by DracoClaw** [12944qwerty/share-plugins#7]
Currently there is `share_plugin` and `share_theme`, they should be merged into `share`. Seeing as themes and plugins share a an `install`, `uninstall`, `enable, and `disable` this only makes sense.

The command for [spotify-modal](https://github.com/replugged-org/spotify-modal) would need to be renamed to something like `share_song` but that's easy enough.

**Comment by DracoClaw** [comment]
Should probably also like, merge this whole thing into replugged core but ¯\_(ツ)_/¯

**Comment by 12944qwerty** [comment]
I think we'd rather merge this and rename the share command

**Comment by DracoClaw** [comment]
It is now integrated natively into Replugged
